### PR TITLE
implemented progress bars

### PR DESCRIPTION
**Pull request by marcograss**
hi, I implemented a simple multi progress bar, one for each thread, with ETA to completion, to have some feedback on how much it's gonna take

### CODE REVIEW

**Comment by marcograss** [comment]
hi, any comment on this?

**Comment by XVilka** [comment]
You can invest your time in https://github.com/radareorg/radare2/issues/10725 instead ;)

**Comment by sgayou** [comment]
I'll look at it eventually, but just fork. This is just a template of a tool to play around with. Probably won't fit your needs by default.

Good luck!

**Comment by sgayou** [comment]
This is neat. Thank you, and apologies about the delay. Been a strange year.

**Comment by sgayou** [comment]
Released 0.1.3 with progress bar support based on this commit. Pass in -p to see progress. Default output should be the same, except I now print more status messages to stderr and only the final results to stdout.

**Pull request merged**
